### ISSUE TITLE
dev版 网络卡顿

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#10]
awa

**Comment by layou233** [comment]
阿这  
由于dev版的版本更新检测还是请求master的，所以dev版反而会提醒过期  
不过无伤大雅，顺便还能提醒你在用dev版XD  
翻译: 懒得改了 避免以后合并了再改回去

**Comment by return60** [comment]
哦

**Comment by return60** [comment]
还有个奇特的问题
就是在ping的界面会卡顿
是在加motd后所产生的

**Comment by layou233** [comment]
能否加入游戏？

**Comment by return60** [comment]
可以加入

**Comment by return60** [comment]
但会概率性卡顿

**Comment by layou233** [comment]
这个可能跟流控有关  
配置里的`Flow`管理流控模式  
设置为origin为Golang原版转发，linux-zerocopy为splice函数转发，auto为自动选择，默认选择linux-zerocopy  
可以改成origin看看是否是zerocopy的锅，splice函数和系统网络设置息息相关，比较难拿捏

**Comment by return60** [comment]
我试试

**Comment by return60** [comment]
可以用qq吗，github有点不方便
