### ISSUE TITLE
如何使ZBProxy加速MCC并正常加入游戏？

### ISSUE THREAD

**Issue by Mengke15** [layou233/ZBProxy#102]
MCC早时接入了Anycast，但是泛播对于某些地区来说并没有降低延迟，于是使用了ZBProxy并成功加速游戏，然后最近MCC禁止了通过VPN/Proxy连接的玩家加入，一但加入，就会显示这些（如图）。
所以如何使ZBProxy加速MCC并正常加入游戏？
![-4e2877cb7ed1639b](https://github.com/layou233/ZBProxy/assets/111745080/e25e80b0-d290-418c-b6f9-12383a1e3801)

**Comment by BiliZheXue** [comment]
@Mengke15 尝试使用域名覆写（但是应该是默认开启的）

**Comment by Mengke15** [comment]
是打开的

**Comment by BiliZheXue** [comment]
@Mengke15 那就不得而知了 ZBProxy的绕过检测很大程度只是针对于Hypixel 对于其他的服务器不能保证完全解锁（或许你可以检查一下IP风险等相关问题 如同Cloudflare也拉黑了很多ip风险较高的ip）

**Comment by OOPSgary** [comment]
> MCC早时接入了Anycast，但是泛播对于某些地区来说并没有降低延迟，于是使用了ZBProxy并成功加速游戏，然后最近MCC禁止了通过VPN/Proxy连接的玩家加入，一但加入，就会显示这些（如图）。 所以如何使ZBProxy加速MCC并正常加入游戏？ ![-4e2877cb7ed1639b](https://user-images.githubusercontent.com/111745080/247117811-e25e80b0-d290-418c-b6f9-12383a1e3801.jpg)

这是IP风险比较高的原因 比较难解决  试图使用一些IP威胁系数低的IP（一般流媒体解锁鸡是比较“安全”的） 来解决这个问题

**Comment by Mengke15** [comment]
好的我试试

**Comment by layou233** [comment]
@Mengke15 应该是服务器启用了 prevent-proxy-connection 功能。要绕过这一检测，你需要保证 客户端与 Mojang 验证服务器的连接 和 客户端到服务器的连接 使用同一 IP，即把整个 MC 进程的所有连接进行代理转发。

技术细节可以看： https://www.spigotmc.org/threads/prevent-proxy-connections-here-is-the-answer.264721/

"If the ISP/AS sent from the MC server differ from what the one authenticated to Mojang's authserver it is blocked"

大意是，如果服务器接收到的客户端 ISP/AS 与我们验证服务器接受到的不同，它将被阻断。

当然，我也不排除服务器使用了其它检测方法的可能性，比如楼上讨论的 IP 风险评估。

**Comment by OOPSgary** [comment]
@layou233 大概情况下不会开启这个选项 很大概率是IP风险问题

**Comment by lycorisor** [comment]
您好，这样的话就不建议使用转发方式进行加速了，加速器是一个更好的办法，或者您可以联系官方进行解决

**Comment by Mengke15** [comment]
> 您好，这样的话就不建议使用转发方式进行加速了，加速器是一个更好的办法，或者您可以联系官方进行解决

加速器效果有时也是不行的，而且也有这种情况。

**Comment by Mengke15** [comment]
> @Mengke15 应该是服务器启用了 prevent-proxy-connection 功能。要绕过这一检测，你需要保证 客户端与 Mojang 验证服务器的连接 和 客户端到服务器的连接 使用同一 IP，即把整个 MC 进程的所有连接进行代理转发。
> 
> 技术细节可以看： https://www.spigotmc.org/threads/prevent-proxy-connections-here-is-the-answer.264721/
> 
> "If the ISP/AS sent from the MC server differ from what the one authenticated to Mojang's authserver it is blocked"
> 
> 大意是，如果服务器接收到的客户端 ISP/AS 与我们验证服务器接受到的不同，它将被阻断。
> 
> 当然，我也不排除服务器使用了其它检测方法的可能性，比如楼上讨论的 IP 风险评估。

我已排除了IP风险原因，如果是这样，我需要怎么做？

**Comment by lycorisor** [comment]
> > @Mengke15 应该是服务器启用了 prevent-proxy-connection 功能。要绕过这一检测，你需要保证 客户端与 Mojang 验证服务器的连接 和 客户端到服务器的连接 使用同一 IP，即把整个 MC 进程的所有连接进行代理转发。
> > 技术细节可以看： https://www.spigotmc.org/threads/prevent-proxy-connections-here-is-the-answer.264721/
> > "If the ISP/AS sent from the MC server differ from what the one authenticated to Mojang's authserver it is blocked"
> > 大意是，如果服务器接收到的客户端 ISP/AS 与我们验证服务器接受到的不同，它将被阻断。
> > 当然，我也不排除服务器使用了其它检测方法的可能性，比如楼上讨论的 IP 风险评估。
> 
> 我已排除了IP风险原因，如果是这样，我需要怎么做？

这种情况需要您搭建代理，通过代理的方式连接到节点

**Comment by layou233** [comment]
> 我已排除了IP风险原因，如果是这样，我需要怎么做？

在落地服务器上搭建代理（如 Shadowsocks），然后使用 Netch 或者 Clash/sing-box TUN 对游戏进程或整个网络环境进行代理。你也可以尝试使用 Java 虚拟机参数指定使用 HTTP 代理。

因此，加速 IP 几乎不能解决这种限制，除非使用 MITM 的形式实现加速 IP。MITM 方式配置复杂、安全性低且效率不佳，ZBProxy 暂未支持。

**Comment by lycorisor** [comment]
https://www.bilibili.com/video/BV1kX4y1a76d
官方已提出解决方案
