### ISSUE TITLE
如何热加载配置文件

### ISSUE THREAD

**Issue by tmdakm** [layou233/ZBProxy#105]
我更改配置文件List中的某一项后，等了差不多一个多小时，后台都没看到有重载的提示，并且测试后也没有添加成功白名单

**Comment by layou233** [comment]
测试后无法复现所述情况。ZBProxy 会监视配置文件的写入事件，并在写入事件触发时开始重载，这通常发生在保存配置文件时。重载时终端会有紫色（如果你的终端支持色彩）日志提示重载。

初步推测为权限限制问题所致，如无法配置文件权限，请确保在 root 权限（Windows 为管理员权限）下重试。如不能解决，请提供运行环境、ZBProxy Build Information、使用的配置文件编辑器以便进一步分析。

**Comment by tmdakm** [comment]
我用root权限重试之后解决了，感谢
