### ISSUE TITLE
功能建议：添加ForceHost

### ISSUE THREAD

**Issue by mckuhei** [layou233/ZBProxy#107]
ForceHost字段方便修改servername，比如说我给TargetAddress填写了1.2.3.4，但是发送服务器地址时如果存在ForceHost字段，那么就把服务器地址修改成ForceHost字段填写的内容，这样子方便IPBan了以后使用端口转发技术让其他服务器转发hypixel的流量以便更换IP绕过IPBan

**Comment by OOPSgary** [comment]
@mckuhei 请你说的详细点 欢迎加入tg群讨论

**Comment by mckuhei** [comment]
大概就是，我有两台服务器，其中一台线路质量较差，IP地址为1.2.3.4，其中一台线路较好，IP地址为2.3.4.5，我在2.3.4.5搭建了ZBProxy，然后我在1.2.3.4中使用了iptables把hypixel的25565端口转发到该服务器的1.2.3.4端口，然后2.3.4.5的目标服务器填写的是1.2.3.4，但是如果填写1.2.3.4那么加入游戏时ZBProxy会向hypixel发送1.2.3.4这个IP地址，然后hypixel拒绝进服，我在想能否在配置文件加个ForceHost字段，直接用这个字段代替TargetAddress发送给Hypixel

**Comment by OOPSgary** [comment]
@mckuhei 欢迎加入TG群即使讨论 你这样太慢了

**Comment by OOPSgary** [comment]
哦 你这个想法就有点荒诞了
首先 你应该是2.3.4.5通过1.2.3.4连接Hypixel以实现代理
其次 请使用A B C代表服务器

**Comment by layou233** [comment]
@mckuhei 你要找的是：RewrittenHostname

参见文档。

**Comment by OOPSgary** [comment]
Rewritten使用Hypixel
然后目标地址填写第二个服务器地址

**Comment by mckuhei** [comment]
好的，知道了，我也很久没更新ZBProxy了
