### ISSUE TITLE
hyp连接超时

### ISSUE THREAD

**Issue by 1665169869** [layou233/ZBProxy#115]
默认配置 已放行25565端口

在多人游戏列表可正常显示服务器状态

![image](https://github.com/layou233/ZBProxy/assets/50762038/3ae53aef-a0a2-465e-bfbb-e448b9e764b1)
![image](https://github.com/layou233/ZBProxy/assets/50762038/4d63af03-4058-42ef-afc5-a5c20f668b67)

**Comment by layou233** [comment]
缺乏信息，如果可以请贴出部署环境和配置。

**Comment by 1665169869** [comment]
> 缺乏信息，如果可以请贴出部署环境和配置。

环境：centos8
内核版本：4.18.0-193.14.2.el8_2.x86_64
配置信息如下：
```json
{
    "Services": [
        {
            "Name": "HypixelDefault",
            "TargetAddress": "mc.hypixel.net",
            "TargetPort": 25565,
            "Listen": 25565,
            "Flow": "auto",
            "IPAccess": {
                "Mode": ""
            },
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "EnableHostnameAccess": false,
                "OnlineCount": {
                    "Max": 5,
                    "Online": -1,
                    "EnableMaxLimit": true
                },
                "NameAccess": {
                    "Mode": ""
                },
                "AnyDestSettings": {},
                "PingMode": "",
                "MotdFavicon": "{DEFAULT_MOTD}",
                "MotdDescription": "§d{NAME}§e service is working on §a§o{INFO}§r\n§c§lProxy for §6§n{HOST}:{PORT}§r"
            },
            "TLSSniffing": {
                "RejectNonTLS": false
            },
            "Outbound": {
                "Type": ""
            }
        }
    ],
    "Lists": {}
}
```

**Comment by layou233** [comment]
配置上应该不存在问题。可能是服务器无法连接至 Hypixel 服务器。再问下你的服务器部署在哪里，能确认其到 Hypixel 服务器的连通性吗？

**Comment by 1665169869** [comment]
> 配置上应该不存在问题。可能是服务器无法连接至 Hypixel 服务器。再问下你的服务器部署在哪里，能确认其到 Hypixel 服务器的连通性吗？

服务器刚购买部署后的时候是可以连接hypixel 用了大概一两天后就无法连接了

**Comment by 1665169869** [comment]
如何直接在服务器测试hypixel的连通性测试？看起来hyp是禁ping的

**Comment by layou233** [comment]
> 如何直接在服务器测试hypixel的连通性测试？看起来hyp是禁ping的

有两种方法：

1. 基于 TCP SYN 的 TCP Ping。这些网络上有现成的可以找。

2. 删除 ZBProxy Minecraft 模块中的 MOTD 相关项，即可从目标服务器直接拉取 MOTD ，从而测试 MOTD 连通性。

**Comment by layou233** [comment]
目前为止暂不能确定是 ZBProxy 方面的问题，暂时 close ，有后续可以继续在下方提供。
