### ISSUE TITLE
ZBProxy-linux-amd64-v1和ZBProxy-linux-amd64-v3有什么区别吗

### ISSUE THREAD

**Issue by huixpp** [layou233/ZBProxy#119]

**Comment by layou233** [comment]
较新的 x86_64 CPU 支持 amd64v3 扩展指令集，包括 AVX2 等一系列 SIMD 指令，可以提升部分性能。若运行环境的 CPU 不支持 amd64v3 指令集，则该版本程序直接无法启动。  
amd64v1 仅使用最基本的 x86_64 指令，可以在所有 x86_64 CPU 上正常运行。

具体 CPU 支持情况列表可以在 https://xanmod.org/ 上查询。

建议可以先试着运行 v3，若无法启动再切换 v1。

**Comment by huixpp** [comment]
谢谢
