### ISSUE TITLE
继承上游服务器MOTD

### ISSUE THREAD

**Issue by Muska-Ami** [layou233/ZBProxy#125]
如题

**Comment by layou233** [comment]
留空 MotdFavicon 和 MotdDescription 即可。也可以直接删除 Minecraft 模块使其作为端口转发。

以上两种方式皆会使 PingMode 失效，并使服务器列表显示玩家到游戏服务器的真实延迟。

**Comment by Muska-Ami** [comment]
建议写入文档，因为翻文档貌似没找到相关说明
