### ISSUE TITLE
修改配置文件后启动时闪退Crash on startup after modifying config file

### ISSUE THREAD

**Issue by YinHaoovo** [layou233/ZBProxy#13]
修改配置文件以后，cmd窗口会出现一行红色报错，随后cmd闪退关闭。

**Comment by layou233** [comment]
我自己尝试的时候也发现了这个问题，此问题在Windows上发生非常频繁，后续发现不是本程序bug，而是由文件保存格式导致的。  
使用记事本编辑的时候，请勿保存为 带有BOM的UTF-8 格式，本作暂时未添加对UTF-8的BOM格式的兼容，这是肇事元凶，可以保存为 不带有BOM的UTF-8。  
当然，也可以使用 ANSI 或者 ASCII 编码直接保存，在这些编码中没有 BOM 设计，但是需要注意是否使用了会导致乱码的字符。

**Comment by layou233** [comment]
这是个长期存在的问题，已在issue中置顶，以供新人参考。  
已关闭，但与此相关的问题仍然可以在下方提出。
