### ISSUE TITLE
Wiki missing messages configs

### ISSUE THREAD

**Issue by dxniloo** [layou233/ZBProxy#148]
I would like to change messages configs, but I am not able to find any wiki on it.
Please help me.

**Comment by BiliZheXue** [comment]
Kick message or ...?

**Comment by BiliZheXue** [comment]
protocol/minecraft/kick.go
this is the path of kick messages
i hope it can help u :)

**Comment by layou233** [comment]
Are you asking about the kick message?
I have trouble coming up with a nice and intuitive message configuration format, so it's hardcoded for now. If you have one, please suggest it. You can fork and change it for now.
For the MOTD message shown on the server list, I think I've explained it well in the documentation. If you still have questions, please elaborate.

**Comment by dxniloo** [comment]
> Are you asking about the kick message? I have trouble coming up with a nice and intuitive message configuration format, so it's hardcoded for now. If you have one, please suggest it. You can fork and change it for now. For the MOTD message shown on the server list, I think I've explained it well in the documentation. If you still have questions, please elaborate.

Yeah sorry if I wasn't clear, I meant the Name Control Kick message, it's hardcoded
