### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by LiteQwQ** [layou233/ZBProxy#15]
![image](https://user-images.githubusercontent.com/86860513/164909677-715259ca-0fc8-4b06-be5d-19dc7c58eae3.png)
错误1

![image](https://user-images.githubusercontent.com/86860513/164909698-76a9f586-880d-474b-ad79-837898c22d39.png)
错误2

服务器端口出入均放行，系统是CentOS 7.6

**Comment by layou233** [comment]
服务端output以及配置？

**Comment by LiteQwQ** [comment]
![image](https://user-images.githubusercontent.com/86860513/164909782-9146c88a-b9a7-4628-a449-c44c13293563.png)
后台

**Comment by LiteQwQ** [comment]
![image](https://user-images.githubusercontent.com/86860513/164909791-67fab84f-de1a-47ce-844f-18b5b45cc609.png)
配置

**Comment by LiteQwQ** [comment]
几乎所有参数都动了，错误依旧

**Comment by layou233** [comment]
可能是因为上次对mc代码的重构造成的，我会很快开始检查代码实现的工作。  
如急用可以下载前几个版本的构建。

**Comment by LiteQwQ** [comment]
好的，谢谢

**Comment by layou233** [comment]
> 几乎所有参数都动了，错误依旧

AnyDest、MojangCapeRequirement目前都是装饰品（  
MojangCapeRequirement本意是达到类似 强制微软MC 的功能，如果强制迁移来的比我的实现更早的话我可能就直接移除这个计划了（

**Comment by layou233** [comment]
问一下：MOTD能正常显示吗

**Comment by layou233** [comment]
已提交相关补丁，并顺便提交了内存泄漏连接泄露方面的修复。  
这个问题应该在最新的构建中修复。 (build # 29)  
请在生产环境中重试，如有任何问题请继续提出，否则我会默认在一周内关闭此issue.

**Comment by XiChenGG** [comment]
2022年4月28日测试使用build #30仍然会出现disconnected

**Comment by XiChenGG** [comment]
您好，我现在正忙，现在不能查看您的邮件，稍后我会自行查看！
