### ISSUE TITLE
rule_index=0 Rule matched，用户无法连接

### ISSUE THREAD

**Issue by CJYKK** [layou233/ZBProxy#158]
环境信息：
- ZBProxy版本：Actions build#136
- 系统：Debian Linux 6.6.59-x64v4-xanmod1 #0~20241101.g5687e21 SMP PREEMPT_DYNAMIC Fri Nov  1 03:01:36 UTC x86_64 GNU/Linux

配置文件：
```json
{
    "Log": {
        "Level": "debug"
    },
    "Services": [
        {
            "Name": "ZBProxy",
            "Listen": 25565
        }
    ],
    "Router": {
        "DefaultOutbound": "RESET",
        "Rules": [
            {
                "Type": "always",
                "Sniff": "minecraft"
            },
            {
                "Type": "MinecraftHostname",
                "Parameter": {
                    "Domain": "hypixel.mcproxy.jp.cjykk.top"
                },
                "Outbound": "Hypixel"
            },
            {
                "Type": "MinecraftHostname",
                "Parameter": {
                    "Domain": "cubecraft.mcproxy.jp.cjykk.top"
                },
                "Outbound": "CubeCraft"
            },
            {
                "Type": "MinecraftHostname",
                "Parameter": {
                    "Domain": "hmn.mcproxy.jp.cjykk.top"
                },
                "Outbound": "HielkeMapsNetwork"
            }
        ]
    },
    "Outbounds": [
        {
            "Name": "Hypixel",
            "TargetAddress": "mc.hypixel.net",
            "TargetPort": 25565,
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "OnlineCount": {
                    "Max": 114514,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "MotdFavicon": "",
                "MotdDescription": "§d§l{NAME}§r §6§l加速线路§r §a(日本)§r §7|§r §8{HOST}§r\n§7Made by§r §b§lCJYKK"
            }
        },
        {
            "Name": "CubeCraft",
            "TargetAddress": "play.cubecraft.net",
            "TargetPort": 25565,
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "OnlineCount": {
                    "Max": 114514,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "MotdFavicon": "",
                "MotdDescription": "§d§l{NAME}§r §6§l加速线路§r §a(日本)§r §7|§r §8{HOST}§r\n§7Made by§r §b§lCJYKK"
            }
        },
        {
            "Name": "HielkeMapsNetwork",
            "TargetAddress": "play.hielkemaps.com",
            "TargetPort": 25565,
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "OnlineCount": {
                    "Max": 114514,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "MotdFavicon": "",
                "MotdDescription": "§d§l{NAME}§r §6§l加速线路§r §a(日本)§r §7|§r §8{HOST}§r\n§7Made by§r §b§lCJYKK"
            }
        }
    ]
}
```

后台日志：
```
service=ZBProxy ip=<我的IP地址>
rule_index=0 Rule matched
outbound=RESET Handled outbound connection
```

客户端截图：
![image](https://github.com/user-attachments/assets/bf77145f-0ef0-4ca7-b7e6-738ab72aac0d)
![image](https://github.com/user-attachments/assets/27e99004-1cb0-40fc-8964-b26520e2b1ce)

请问配置文件有什么问题吗？

**Comment by layou233** [comment]
域名使用 SRV 解析了吗？

**Comment by CJYKK** [comment]
> 域名使用 SRV 解析了吗？

没有，是直接解析的
![image](https://github.com/user-attachments/assets/75ed57c6-ae77-4c8b-bb2e-bc0a1427503c)
抱歉打这么抽象的码，因为之前被打过……

**Comment by layou233** [comment]
本地似乎不能复现。这个是只有 IPv6 的服务器吗？我倒是没有测试过只有 IPv6 的环境。

**Comment by CJYKK** [comment]
> 本地似乎不能复现。这个是只有 IPv6 的服务器吗？我倒是没有测试过只有 IPv6 的环境。

是的，这是一个仅v6的服务器。
实际上，这还挺玄学的（
之前的服务器只代理 Hypixel 和 CubeCraft，能够正常运行。加了 Hielke Maps Network 以后就连不上了，回滚到之前的 config  依然连不上……

**Comment by layou233** [comment]
> 加了 Hielke Maps Network 以后就连不上了，回滚到之前的 config 依然连不上……

完全重启 ZBProxy 进程了吗？还是就是热重载。

**Comment by CJYKK** [comment]
> > 加了 Hielke Maps Network 以后就连不上了，回滚到之前的 config 依然连不上……
> 
> 完全重启 ZBProxy 进程了吗？还是就是热重载。

写了 systemd
```service
[Unit]
Description=ZBProxy
After=network.target

[Service]
Type=simple
ExecStart=/opt/ZBProxy/ZBProxy-linux-amd64-v3
WorkingDirectory=/opt/ZBProxy
RestartSec=3
DynamicUser=true
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```
用的是`systemctl restart ZBProxy`
所以应该是完全重启吧……

**Comment by pp0236** [comment]
你有没有试过在末尾添加"\u0000FML\u0000"? forge 总是在hostname中添加它。
不确定是否适用于 1.20.4, 但适用于 1.8.9
编辑： 1.13+ forge 客户端使用 "\u0000FML2\u0000"
have you try adding "\u0000FML\u0000" at the end of domain? forge always have it in hostname.
not sure for 1.20.4 but for 1.8.9 it is working

**Comment by layou233** [comment]
@pp0236 Nice catch. We already handle FML signature correctly in legacy outbound, but don't seem to be handling this in the rules.

I'll patch it soon. Thank you for your comment. :-)

**Comment by CJYKK** [comment]
> 你有没有试过在末尾添加"\u0000FML\u0000"? forge 总是在hostname中添加它。 不确定是否适用于 1.20.4, 但适用于 1.8.9 have you try adding "\u0000FML\u0000" at the end of domain? forge always have it in hostname. not sure for 1.20.4 but for 1.8.9 it is working

Yay! I switched to a Fabric client and it worked!
Thanks for your help!

**Comment by layou233** [comment]
The FML markup diffs between versions are a COMPLETE MESS, and wiki.vg obviously doesn't include everything from newer versions. We'll need time to investigate that. But lower versions (at least up to 1.14 I guess) don't have the problem. NeoForge 1.20.4+ doesn't have the problem either.

**Comment by layou233** [comment]
Fixed in 57d61b1.
