### ISSUE TITLE
解决游戏客户端的域名检测

### ISSUE THREAD

**Issue by HundSimon** [layou233/ZBProxy#162]
badlion客户端集成了很多有用的skyblock功能 但这些功能无法正常使用
我猜测可能是域名检测之类的，没有检测到当前服务器是skyblock
请问这个问题该如何解决？

**Comment by pp0236** [comment]
%appdata%\\.minecraft\badlion_settings.json
在此处添加您的域名regex (用户需要在本地编辑badlion配置文件, 我想没有其他办法了)
![image](https://github.com/user-attachments/assets/29a412e8-9c52-40db-b40f-3010c2189d83)

https://support.badlion.net/hc/en-us/articles/14442256625170-Using-Badlion-Client-on-Hypixel-through-a-Proxy

**Comment by layou233** [comment]
Badlion 的解决方法同上。

我听说过 Lunar 的另一种解决方案，即设置服务器的 DNS 记录（如“hypixel.net.yourdomain.com”），并使用 SRV 使其变得漂亮。

**Comment by HundSimon** [comment]
解决了 谢谢
