### ISSUE TITLE
[Bug反馈] labymod无法ping通域名分流的zbproxy

### ISSUE THREAD

**Issue by NikoCat233** [layou233/ZBProxy#163]
感觉是labymod的问题
route配置的always sniff minecraft
minecraft domain 域名分流
default outbound reset

labymod 1.8 legecy 表现为始终reset

**Comment by layou233** [comment]
Minecraft 有时不在服务器列表请求中发送域名，可以加一个 MinecraftStatus 的兜底规则。

**Comment by NikoCat233** [comment]
这个问题好像系3.1-beta1独有的
我在更新到3.1-beta2后就恢复正常了

**Comment by NikoCat233** [comment]
Resolved
更新到3.1-beta2解决
