### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#2]
我目前已执行启动文件，无法直击链接
-系统 centos7
-客户端 badlion

**Comment by layou233** [comment]
麻烦提供更详细的信息以便我分析问题。  
- centos是否有使用bbr等流控软件，或进行了相关网络配置优化？  
- 是否能确认您服务器的25565端口已对因特网开放，并放开linux防火墙，能流畅进行TCP连接？  
- 游戏版本是否为1.9及以上版本，如是，是否尝试过1.8.9能否连接？  
- 是否使用screen等类似程序保证软件能不因SSH登出等其它原因终止运行？（本程序本身不自带后台驻留/systemctl功能）
也可以提供其它可能与解决问题相关的线索方便我分析。

**Comment by return60** [comment]
我使用了暴力BBR魔改版加速
已确认开放了所有端口并且关闭了linux防火墙
我一直都在使用1.8.9进行连接
没有使用screen等软件
使用了宝塔且放行了1:65535端口


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "layou233/ZBProxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月11日(星期天) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [layou233/ZBProxy] 怎么使用 (#2)





 
麻烦提供更详细的信息以便我分析问题。
  
centos是否有使用bbr等流控软件，或进行了相关网络配置优化？
 
是否能确认您服务器的25565端口已对因特网开放，并放开linux防火墙，能流畅进行TCP连接？
 
游戏版本是否为1.9及以上版本，如是，是否尝试过1.8.9能否连接？
 
是否使用screen等类似程序保证软件能不因SSH登出等其它原因终止运行？（本程序本身不自带后台驻留/systemctl功能）
 也可以提供其它可能与解决问题相关的线索方便我分析。

**Comment by layou233** [comment]
由于程序为前台软件，所以和minecraft server一样需要另挂screen进行后台运行。  
请自行搜索screen使用教程，使用`screen -R`等类似指令打开一个screen后在screen中运行本程序，以保证进程不被杀死。  
请勿退出程序（如使用ctrl-c指令），因为一旦本程序退出，相应的监听、转发也会被停止。  
如有需要请连按ctrl-a + ctrl-d退出并挂起screen。  
（理论上，如果ssh一直没有登出的话也不会杀死进程）

**Comment by return60** [comment]
非常感谢您的帮助
我可以推广您的插件吗？

**Comment by layou233** [comment]
> 非常感谢您的帮助
> 我可以推广您的插件吗？

本程序遵循Apache-2.0协议开源，只要在保证我版权信息不被侵害的情况下，即可随意推广发放~

**Comment by return60** [comment]
非常感谢
