### ISSUE TITLE
新分支的Lists格式

### ISSUE THREAD

**Issue by BiliZheXue** [layou233/ZBProxy#28]
想问一下https://github.com/layou233/ZBProxy/tree/new-config的白名单Lists的标准格式
试了一些常见的格式都不行
麻烦了

**Comment by layou233** [comment]
https://github.com/layou233/ZBProxy/issues/3#issuecomment-1125726403  
先参考阅读这个😊

**Comment by layou233** [comment]
提问者本人已在TG群解决问题，同时官方文档也更新了，此issue关闭。
