### ISSUE TITLE
可以写一个白名单吗

### ISSUE THREAD

**Issue by PCD-01** [layou233/ZBProxy#3]
建议配置文件使用yml格式,让用户可以选择开启与否,还可以选择sqlite或者mysql(SQL Server对于Linux不太友好,所以不建议做),希望大佬能加上这个功能(我不太会说话qwq可能有点唐突了)

**Comment by layou233** [comment]
已收到.  
yml或者json格式的配置文件在计划中，白名单功能也是我期望实现的功能之一。  
但是本软件的设计意图是简化搭建加速ip的过程，包括sql连接之类的功能可能会使软件本身变得更复杂（因为我最近也在参与编写付费加速IP软件qaq），所以我将来**可能**会打算使用最原始的格式，比如一行一个名字的txt文件，来实现白名单功能，见谅，因为实现起来真的很简单，用起来也很方便。  
学生狗，比较忙，当然我也是一个懒人(狗头)   
总之，感谢你对本项目的关注!

**Comment by PCD-01** [comment]
(学习C艹的我表示羡慕其他语言,C艹居然没有标准语言库)

**Comment by layou233** [comment]
配置文件功能终于已经实现，现在对当初白名单设计方法预想并不是特别满意，需要进一步讨论如何设计白名单功能

**Comment by ndxzzy** [comment]
> 配置文件的预配置功能终于，现在对已经开始设计的白设计方法想特别欣赏，需要进一步如何设计白实现功能

貌似直至现在依然没有白名单功能

**Comment by layou233** [comment]
> > 配置文件的预配置功能终于，现在对已经开始设计的白设计方法想特别欣赏，需要进一步如何设计白实现功能
> 
> 貌似直至现在依然没有白名单功能

会有的，会有的，我没关issue也没失踪我就迟早会去想想怎么做...  
最近在搞性能相关，白名单这回事有点想不来，和我当时第一个回复想的一样，我一直在SQL白名单和plain text白名单之间有纠结，SQL会提升部署和维护难度，但是plain text会显得杂乱，以及性能瓶颈问题。这里面还需要斟酌。  
目前 ZBProxy 编译的无依赖二进制文件已经达到 7 MB 左右大小，接近我接受能力的极限，我后续还可能做简化工作，所以对引入 SQL 依赖我心里还是有芥蒂，这些事情一直困扰我，所以进度被搁置了。  
我欢迎更多的人加入这方面的讨论，无论是技术人员还是小白，白名单是加速IP非常重要的功能，我会引起重视！

**Comment by ndxzzy** [comment]
> > > 配置文件的预配置功能，现在对已经开始设计的白设计方法想特别欣赏，需要进一步如何设计白实现功能
> > 
> > 
> > 看似现在仍然没有白名单功能
> 
> 有点的，会有的，没有问题的，我就早会去想怎么做... 最近搞的性能相关，所以，我和我自己没想不来，当时第一个回复想我在 SQL 白话里有什么区别，但是在 SQL 白话之间还有话费，在 SQL 文本中会自动提升和部署维护文本，同时会提高部署和维护文本，以及性能问题。这里面需要考虑。 目前 Z 编译的无话可说，这些文件还已经对实现了左右，近我的能力，让我能够实现 SQL 的工作能力，让我有信心，让我相信自己有能力，让我相信自己有能力实现 。欢迎更多的人参与这方面的讨论，不管是技术人员还是小白，白部是加速非常重要的功能，我会参与其中的IP！

希望暑假前可以写出来，支持你！

**Comment by GuyuLiGary** [comment]
layou加油 火速超过mcnser
实测性能比mcnser好
（来自一个内鬼的描述）

**Comment by LiteQwQ** [comment]
> layou加油 火速超过mcnser 实测性能比mcnser好 （来自一个内鬼的描述）

捕捉

**Comment by GuyuLiGary** [comment]
但是也有114514个bug（（（

**Comment by layou233** [comment]
> 但是也有114514个bug（（（
> 

什么bug...

**Comment by layou233** [comment]
目前我个人打算在配置文件中添加一个`Lists`项，和`Services`同级，具体内容如下：  
```json
"Lists": {
    "list1": ["foo", "bar"],
    "listN": ["apple", "banana"],
    "IPs": ["1.1.1.1", "127.0.0.1"]
    ......
}
```  
`Lists`可以通过键值对（或者称之为 JSON对象）的方法存储多个String List，这些list本身是无意义的，但可以在服务中被引用（通过 键名），从而把黑/白名单绑定到一个list上。多个服务可以引用同一个list，不会产生任何问题。  
这样做，我可以顺便把IP黑/白名单一同实现了，同时`Lists`也具有很大的可扩展性，可以作为以后其它问题解决方案的思维导向。

**Comment by layou233** [comment]
相关代码更改正在`new-config`分支中进行，本次更新预计会对现有配置文件进行较大改动。主要是顺便分类整理了一下配置文件内容，不然太乱了。

**Comment by layou233** [comment]
白名单功能已经出了，现在已位于主分支，此issue已解决。
