### ISSUE TITLE
Access object

### ISSUE THREAD

**Issue by ChaRoSaMa** [layou233/ZBProxy#31]
能详细介绍下mode属性咋用吗

**Comment by niniubiwoc** [comment]
mode有三种属性
1.若不填则表示为Default属性，这种情况该功能为关闭状态
2.填allow或whitelist时，为白名单模式，这种情况只有在配置中填写了玩家名或ip才能进入
3.填block或blacklist时，为黑名单模式，这种情况在配置中填写的玩家名或ip都不能进入
未来会开发混合模式

**Comment by layou233** [comment]
> 未来会开发混合模式

Mixed mode is not planned in current plan.  
Reason: Allow mode and Block mode already meet all cases I have thought of.
