### ISSUE TITLE
自己编译后报错

### ISSUE THREAD

**Issue by LiteQwQ** [layou233/ZBProxy#37]
报错 **/lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./main**

**Comment by layou233** [comment]
这个应该跟本程序无关，跟运行环境有关，猜猜是go编译器找不到需要的依赖（C运行时），请补全/更新libc运行时，或者使用较新的系统重试。  
Ubuntu 20.04/22.04、Debian 10+等  
不建议用CentOS，这个系统很快就会过时。

**Comment by OOPSgary** [comment]
我自己编译没问题
Debian11 安装go1.18.3
github对于中国境内访问的确慢

**Comment by layou233** [comment]
> 我自己编译没问题
> Debian11 安装go1.18.3
> github对于中国境内访问的确慢

他应该是使用了较旧的系统运行，自己编译时没有进行静态编译，但运行的机子 C运行时版本太低，运行不动。

**Comment by OOPSgary** [comment]
> > 我自己编译没问题
> > Debian11 安装go1.18.3
> > github对于中国境内访问的确慢
> 
> 他应该是使用了较旧的系统运行，自己编译时没有进行静态编译，但运行的机子 C运行时版本太低，运行不动。

我私聊过了
他是忘记go mod tidy了
bruhhhhh

**Comment by LiteQwQ** [comment]
用windows的linux子系统编译成功

**Comment by layou233** [comment]
> 用windows的linux子系统编译成功

其实没必要，ZBProxy没有任何CGO代码，完全可以使用go的交叉编译功能直接在Windows上完成对目标平台`linux/amd64`的编译。

**Comment by niniubiwoc** [comment]
有没有一种可能，它其实不会set GOOS=linux

**Comment by OOPSgary** [comment]
有没有一种可能
没运行
go mod tidy

**Comment by OOPSgary** [comment]
> 有没有一种可能，它其实不会set GOOS=linux

![Uploading 0AA7983B-F813-41C5-A3F4-081EE7C5AABE.jpeg…]()

**Comment by layou233** [comment]
> 有没有一种可能，它其实不会set GOOS=linux

这个还是cmd指令。。快进到powershell

**Comment by OOPSgary** [comment]
不是 似乎他真的没有
go mod tidy

**Comment by niniubiwoc** [comment]
你奶奶，别有没有可能了，火速写码字去
