### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by Shizuri23** [layou233/ZBProxy#4]
![](https://cdn.jsdelivr.net/gh/ShiZuRi23/ImgNMSL/img/20210730230312.png)
![](https://cdn.jsdelivr.net/gh/ShiZuRi23/ImgNMSL/img/20210730230232.png)
Linux服务器，已排除防火墙问题
![30EB2242BC0C5CF070C81F7154F05090](https://user-images.githubusercontent.com/46082179/127672905-ce5df427-cd8d-4063-a409-395288859c35.jpg)

**Comment by layou233** [comment]
游戏版本是否为1.8.9？

**Comment by Shizuri23** [comment]
> 游戏版本是否为1.8.9？

版本为1.17.1

**Comment by layou233** [comment]
> > 游戏版本是否为1.8.9？
> 
> 版本为1.17.1

很抱歉，但是更新的版本不受支持.  
(不支持的版本范围：协议号为128及以上的版本)

**Comment by Shizuri23** [comment]
> > > 游戏版本是否为1.8.9？
> > 
> > 
> > 版本为1.17.1
> 
> 很抱歉，但是更新的版本不受支持.
> (不支持的版本范围：协议号为128及以上的版本)

这样啊，记得标记下～ 协议号128以以上是啥版本

**Comment by layou233** [comment]
这个问题由于一个很易于理解的问题导致:  
协议号为128及以上的数字，在编码为varint时会占用两个字节，但是事实上本程序在编写的时候犯了一个先入为主的错误，即把协议号视为一个字节，导致了定位错误。  
由于开发时测试的版本为1.8.9(协议号47)，所以问题并没有发生.  
协议号128的版本应该是在1.9.4到1.10之间

**Comment by layou233** [comment]
刚放学，看到一个fork已经帮助我解决了protocol  number 的问题  
[https://github.com/9ikj/ZBProxy](https://github.com/9ikj/ZBProxy)  
在这里感谢一下 @9ikj ，应该也是一位中国人，不错的补丁程序  
但是鉴于我本人事实上已经有对于当前主分支的代码进行了部分修改，等待发布2.0版本，所以请见谅，目前无合并分支的打算，并非出于其它原因。  
如果有需要使用高版本代理的可以使用这位仁兄的版本  
（呃不过我可能会咕咕比较长的一段时间，刚进入高中不太适应住宿生活和学习节奏，虚的很，时间也比较少）

**Comment by layou233** [comment]
The bug mentioned was fixed two versions ago.  
No longer pin this issue.
