### ISSUE TITLE
玩家Logs文件中出现Unexpected packet during modded negotiation - assuming vanilla or keepalives:(这个包的名字)的错误

### ISSUE THREAD

**Issue by DreamwareN** [layou233/ZBProxy#40]
先附上一段Log:
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S37PacketStatistics
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S05PacketSpawnPosition
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S39PacketPlayerAbilities
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S09PacketHeldItemChange
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams
[18:18:19] [Netty Client IO #6/INFO]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S3EPacketTeams

这个bug进了服务器就会有
玩久之后log文件超级大(几百mb)
client收到啥包都报错

我用的forge版本为11.15.1.1722 Minecraft版本为1.8.9

**Comment by layou233** [comment]
已收到，明天再看（

**Comment by OOPSgary** [comment]
> 先问一下： 游戏能正常进行吗？还是直接没法进入了？

直接崩溃

**Comment by niniubiwoc** [comment]
问一下不用ZBProxy代理不会出现报错是吗

**Comment by DreamwareN** [comment]
> 先问一下： 游戏能正常进行吗？还是直接没法进入了？

我数了一下这种报错log输出挺快的
1秒2000多行log输出 全是这种

**Comment by DreamwareN** [comment]
> 问一下不用ZBProxy代理不会出现报错是吗

是的

**Comment by niniubiwoc** [comment]
服务器是否有正版登录

**Comment by DreamwareN** [comment]
> 服务器是否有正版登录

有

**Comment by niniubiwoc** [comment]
若修改重试后无效果，请检查是否是某些mod导致的
https://forums.minecraftforge.net/topic/24820-unexpected-packet-during-modded-negotiation-fixed/
https://www.mcbbs.net/forum.php?mod=viewthread&tid=562399
https://github.com/MinecraftForge/MinecraftForge/issues/4913
这些问题看起来只是会在使用forge的客户端上出现
ZBProxy只会在握手阶段修改您的数据包，若进行正版验证则后续数据包都为加密形式，若数据包出问题则会导致解密错误进而直接退出服务器
而这些报错信息看起来是正常解密之后某部分读取数据不正常而造成的

**Comment by DreamwareN** [comment]
确实修改后无效果

**Comment by DreamwareN** [comment]
> 若修改重试后无效果，请检查是否是某些mod导致的 https://forums.minecraftforge.net/topic/24820-unexpected-packet-during-modded-negotiation-fixed/ https://www.mcbbs.net/forum.php?mod=viewthread&tid=562399 [MinecraftForge/MinecraftForge#4913](https://github.com/MinecraftForge/MinecraftForge/issues/4913) 这些问题看起来只是会在使用forge的客户端上出现 ZBProxy只会在握手阶段修改您的数据包，若进行正版验证则后续数据包都为加密形式，若数据包出问题则会导致解密错误进而直接退出服务器 而这些报错信息看起来是正常解密之后某部分读取数据不正常而造成的

但是我不装任何mod还是这个样子

**Comment by DreamwareN** [comment]
我确认这是forge的问题 因为我用原版客户端没有出现此报错

**Comment by DreamwareN** [comment]
> 若修改重试后无效果，请检查是否是某些mod导致的 https://forums.minecraftforge.net/topic/24820-unexpected-packet-during-modded-negotiation-fixed/ https://www.mcbbs.net/forum.php?mod=viewthread&tid=562399 [MinecraftForge/MinecraftForge#4913](https://github.com/MinecraftForge/MinecraftForge/issues/4913) 这些问题看起来只是会在使用forge的客户端上出现 ZBProxy只会在握手阶段修改您的数据包，若进行正版验证则后续数据包都为加密形式，若数据包出问题则会导致解密错误进而直接退出服务器 而这些报错信息看起来是正常解密之后某部分读取数据不正常而造成的

只要是forge 都会报错 没装mod一样报错

**Comment by DreamwareN** [comment]
然后报错的log里面没有 关于C00PacketKeepAlive包的报错

**Comment by layou233** [comment]
我对Forge端的抓包研究太少了，这方面还得再研究。

**Comment by niniubiwoc** [comment]
https://github.com/layou233/ZBProxy/actions/runs/2680084277
下载该debug版本，并在config里面添加字段`"debug":true,`
将输出的log提交给我们，以帮助我们更好的定位bug

**Comment by DreamwareN** [comment]
我测试了一下还是出现一样的问题
但是这次进服务器时候会出现错误 进入服务器有几率被踢出(看log里面有)
[https://github.com/DreamwareN/buglogs](url)

**Comment by DreamwareN** [comment]
[这个链接才能点...](https://github.com/DreamwareN/buglogs)

**Comment by niniubiwoc** [comment]
您好，方便的话进telegram群聊
https://t.me/launium

**Comment by DreamwareN** [comment]
> 您好，方便的话进telegram群聊 https://t.me/launium

有点困难 因为我的手机 开机键老化 坏掉了 无法开机
我还只是个学生 所以近段时间无法使用t . g

**Comment by DreamwareN** [comment]
> 我对Forge端的抓包研究太少了，这方面还得再研究。

我想 是不是 ZBProxy用go-mc处理login数据包
把login数据包重组了
Forge客户端发的login包和ZBProxy处理后的login包不一样
导致ZBProxy发的login数据包和原版客户端发的login包一样
然后hyp以为玩家根本没有装Forge 就用非Forge的方式通信
然后玩家收到没有Forge信息的数据包
就开始出错了

所以forge端发的login数据包有没有可能和原版不一样?

**Comment by niniubiwoc** [comment]
https://github.com/layou233/ZBProxy/actions/runs/2680084277
下载该debug版本，并在config里面添加字段`"debug":true,`
将输出的log提交给我们，以帮助我们更好的定位bug

用这个版本的ZBProxy啊
然后把输出的日志信息发过来啊
我不是tm说了吗，不是让你发客户端的log，客户端的log能看出什么，发ZBProxy的日志信息过来

**Comment by DreamwareN** [comment]
Welcome to ZBProxy 3.0-rc.2!
Build Information: go1.18.3, linux/amd64
2022/07/17 22:06:17 Successfully loaded config from file.
2022/07/17 22:06:17 Flow mode : auto
Your ZBProxy is up-to-date. Have fun!
2022/07/17 22:07:26 Service HypixelDefault : A new connection request sent by 127.0.0.1:11338 is received.
2022/07/17 22:07:26 Using Minecraft Autofix packs mode
2022/07/17 22:07:26 Handshake Packet Start
2022/07/17 22:07:26 Protocol Code : 47
2022/07/17 22:07:26 Hostname : 127.0.0.1FML
2022/07/17 22:07:26 Port : 25565
2022/07/17 22:07:26 State Code : 1
2022/07/17 22:07:26 Get motd by local
2022/07/17 22:07:26 Service HypixelDefault : A connection with 127.0.0.1:11338 is closed.
2022/07/17 22:07:31 Service HypixelDefault : A new connection request sent by 127.0.0.1:11354 is received.
2022/07/17 22:07:31 Using Minecraft Autofix packs mode
2022/07/17 22:07:31 Handshake Packet Start
2022/07/17 22:07:31 Protocol Code : 47
2022/07/17 22:07:31 Hostname : 127.0.0.1FML
2022/07/17 22:07:31 Port : 25565
2022/07/17 22:07:31 State Code : 2
2022/07/17 22:07:31 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:07:36 Service HypixelDefault : A connection with 127.0.0.1:11354 is closed.
2022/07/17 22:07:49 Service HypixelDefault : A new connection request sent by 127.0.0.1:11383 is received.
2022/07/17 22:07:49 Using Minecraft Autofix packs mode
2022/07/17 22:07:49 Handshake Packet Start
2022/07/17 22:07:49 Protocol Code : 47
2022/07/17 22:07:49 Hostname : 127.0.0.1FML
2022/07/17 22:07:49 Port : 25565
2022/07/17 22:07:49 State Code : 2
2022/07/17 22:07:49 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:07:52 Service HypixelDefault : A connection with 127.0.0.1:11383 is closed.
2022/07/17 22:07:58 Service HypixelDefault : A new connection request sent by 127.0.0.1:11408 is received.
2022/07/17 22:07:58 Using Minecraft Autofix packs mode
2022/07/17 22:07:58 Handshake Packet Start
2022/07/17 22:07:58 Protocol Code : 47
2022/07/17 22:07:58 Hostname : 127.0.0.1FML
2022/07/17 22:07:58 Port : 25565
2022/07/17 22:07:58 State Code : 2
2022/07/17 22:07:58 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:01 Service HypixelDefault : A connection with 127.0.0.1:11408 is closed.
2022/07/17 22:08:02 Service HypixelDefault : A new connection request sent by 127.0.0.1:11422 is received.
2022/07/17 22:08:02 Using Minecraft Autofix packs mode
2022/07/17 22:08:02 Handshake Packet Start
2022/07/17 22:08:02 Protocol Code : 47
2022/07/17 22:08:02 Hostname : 127.0.0.1FML
2022/07/17 22:08:02 Port : 25565
2022/07/17 22:08:02 State Code : 2
2022/07/17 22:08:02 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:04 Service HypixelDefault : A connection with 127.0.0.1:11422 is closed.
2022/07/17 22:08:06 Service HypixelDefault : A new connection request sent by 127.0.0.1:11427 is received.
2022/07/17 22:08:06 Using Minecraft Autofix packs mode
2022/07/17 22:08:06 Handshake Packet Start
2022/07/17 22:08:06 Protocol Code : 47
2022/07/17 22:08:06 Hostname : 127.0.0.1FML
2022/07/17 22:08:06 Port : 25565
2022/07/17 22:08:06 State Code : 2
2022/07/17 22:08:06 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:09 Service HypixelDefault : A connection with 127.0.0.1:11427 is closed.
2022/07/17 22:08:11 Service HypixelDefault : A new connection request sent by 127.0.0.1:11440 is received.
2022/07/17 22:08:11 Using Minecraft Autofix packs mode
2022/07/17 22:08:11 Handshake Packet Start
2022/07/17 22:08:11 Protocol Code : 47
2022/07/17 22:08:11 Hostname : 127.0.0.1FML
2022/07/17 22:08:11 Port : 25565
2022/07/17 22:08:11 State Code : 2
2022/07/17 22:08:11 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:13 Service HypixelDefault : A connection with 127.0.0.1:11440 is closed.
2022/07/17 22:08:21 Service HypixelDefault : A new connection request sent by 127.0.0.1:11458 is received.
2022/07/17 22:08:21 Using Minecraft Autofix packs mode
2022/07/17 22:08:21 Handshake Packet Start
2022/07/17 22:08:21 Protocol Code : 47
2022/07/17 22:08:21 Hostname : 127.0.0.1FML
2022/07/17 22:08:21 Port : 25565
2022/07/17 22:08:21 State Code : 2
2022/07/17 22:08:21 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:24 Service HypixelDefault : A connection with 127.0.0.1:11458 is closed.
2022/07/17 22:08:27 Service HypixelDefault : A new connection request sent by 127.0.0.1:11468 is received.
2022/07/17 22:08:27 Using Minecraft Autofix packs mode
2022/07/17 22:08:27 Handshake Packet Start
2022/07/17 22:08:27 Protocol Code : 47
2022/07/17 22:08:27 Hostname : 127.0.0.1FML
2022/07/17 22:08:27 Port : 25565
2022/07/17 22:08:27 State Code : 2
2022/07/17 22:08:27 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:47 Service HypixelDefault : A connection with 127.0.0.1:11468 is closed.
2022/07/17 22:08:54 Service HypixelDefault : A new connection request sent by 127.0.0.1:11524 is received.
2022/07/17 22:08:54 Using Minecraft Autofix packs mode
2022/07/17 22:08:54 Handshake Packet Start
2022/07/17 22:08:54 Protocol Code : 47
2022/07/17 22:08:54 Hostname : 127.0.0.1FML
2022/07/17 22:08:54 Port : 25565
2022/07/17 22:08:54 State Code : 2
2022/07/17 22:08:54 Service HypixelDefault : A new Minecraft player requested a login: 4000years [DEFAULT]
2022/07/17 22:08:58 Service HypixelDefault : A connection with 127.0.0.1:11524 is closed.

**Comment by layou233** [comment]
@DreamwareN 我以前粗略观察过Forge端的前几个登录包的行为。并且有一个跟Forge端兼容性的问题，已经在上一次IgnoreFMLSuffix更新的时候修复了。此项设为false时理论上兼容Forge端登录。  
加密请求后续的包和ZBProxy处理无关，因为这些包都是完全加密的，ZBProxy并没有且当前无法将其解密并进行修改。我的目光会放在前面几个包。  
问题就出在，就那么几个包为什么会有问题。。

**Comment by layou233** [comment]
我和 @niniubiwoc 讨论了一下，请检查`IgnoreFMLSuffix`是否为false，如不是请按此设置，或者直接删除该条目。这可能对FML服务器兼容性很重要。

**Comment by DreamwareN** [comment]
Welcome to ZBProxy 3.0-rc.2!
Build Information: go1.18.3, linux/amd64
2022/07/17 22:29:45 Successfully loaded config from file.
2022/07/17 22:29:45 Flow mode : auto
Your ZBProxy is up-to-date. Have fun!
2022/07/17 22:29:47 Service HypixelDefault : A new connection request sent by 127.0.0.1:14679 is received.
2022/07/17 22:29:47 Using Minecraft Autofix packs mode
2022/07/17 22:29:47 Handshake Packet Start
2022/07/17 22:29:47 Protocol Code : 47
2022/07/17 22:29:47 Hostname : 127.0.0.1FML
2022/07/17 22:29:47 Port : 25565
2022/07/17 22:29:47 State Code : 1
2022/07/17 22:29:47 Get motd by local
2022/07/17 22:29:47 Service HypixelDefault : A connection with 127.0.0.1:14679 is closed.
2022/07/17 22:29:52 Service HypixelDefault : A new connection request sent by 127.0.0.1:14702 is received.
2022/07/17 22:29:52 Using Minecraft Autofix packs mode
2022/07/17 22:29:52 Handshake Packet Start
2022/07/17 22:29:52 Protocol Code : 47
2022/07/17 22:29:52 Hostname : 127.0.0.1FML
2022/07/17 22:29:52 Port : 25565
2022/07/17 22:29:52 State Code : 2
2022/07/17 22:29:52 Service HypixelDefault : A new Minecraft player requested a login: ATP_NADPH [DEFAULT]
2022/07/17 22:29:56 Service HypixelDefault : A connection with 127.0.0.1:14702 is closed.
2022/07/17 22:30:08 Service HypixelDefault : A new connection request sent by 127.0.0.1:14726 is received.
2022/07/17 22:30:08 Using Minecraft Autofix packs mode
2022/07/17 22:30:08 Handshake Packet Start
2022/07/17 22:30:08 Protocol Code : 47
2022/07/17 22:30:08 Hostname : 127.0.0.1FML
2022/07/17 22:30:08 Port : 25565
2022/07/17 22:30:08 State Code : 2
2022/07/17 22:30:08 Service HypixelDefault : A new Minecraft player requested a login: ATP_NADPH [DEFAULT]
2022/07/17 22:30:13 Service HypixelDefault : A connection with 127.0.0.1:14726 is closed.
2022/07/17 22:30:17 Service HypixelDefault : A new connection request sent by 127.0.0.1:14747 is received.
2022/07/17 22:30:17 Using Minecraft Autofix packs mode
2022/07/17 22:30:17 Handshake Packet Start
2022/07/17 22:30:17 Protocol Code : 47
2022/07/17 22:30:17 Hostname : 127.0.0.1FML
2022/07/17 22:30:17 Port : 25565
2022/07/17 22:30:17 State Code : 2
2022/07/17 22:30:17 Service HypixelDefault : A new Minecraft player requested a login: ATP_NADPH [DEFAULT]
2022/07/17 22:31:23 Service HypixelDefault : A connection with 127.0.0.1:14747 is closed.
2022/07/17 22:31:23 Service HypixelDefault : A new connection request sent by 127.0.0.1:14874 is received.
2022/07/17 22:31:23 Using Minecraft Autofix packs mode
2022/07/17 22:31:23 Handshake Packet Start
2022/07/17 22:31:23 Protocol Code : 47
2022/07/17 22:31:23 Hostname : 127.0.0.1FML
2022/07/17 22:31:23 Port : 25565
2022/07/17 22:31:23 State Code : 1
2022/07/17 22:31:23 Get motd by local
2022/07/17 22:31:23 Service HypixelDefault : A connection with 127.0.0.1:14874 is closed.

按此设置IgnoreFMLSuffix=false ZBProxy输出的内容

mc的log输出中一样是报错

**Comment by layou233** [comment]
https://github.com/layou233/ZBProxy/actions/runs/2685840351  
刚才修复了一个关于这个判断的问题，再试试？

**Comment by DreamwareN** [comment]
一样报错

**Comment by DreamwareN** [comment]
IgnoreFMLSuffix=false IgnoreFMLSuffix=true 都试了

**Comment by niniubiwoc** [comment]
那大概率就是您的forge的问题了，我们平时用forge客户端都没出问题，而且那个字段只是对强制要求FORGE客户端进行校验，像hypixel这种可要可不要的都没有什么关系，况且你还能进去

**Comment by DreamwareN** [comment]
> 那大概率就是您的forge的问题了，我们平时用forge客户端都没出问题，而且那个字段只是对强制要求FORGE客户端的服务端进行校验，像hypixel这种可要可不要的都没有什么关系，况且你还能进去

而且不只是我一个人有这个问题

**Comment by layou233** [comment]
根据Forge官网显示，1.8.9最新的Forge版本为11.15.1.2318（以下简称2318版本）。这是1.8.9版本下的最后一个Forge更新，发布于5年前，且在去年（或者前年，忘了）被设定为推荐的版本。  
我们调试所用的1.8.9 Forge端，版本均为2318，由于此版已被大多数客户端采用，所以更旧的Forge版本不在我们的兼容性考虑范围内。  
详情： https://files.minecraftforge.net/net/minecraftforge/forge/index_1.8.9.html  
在一楼，我看到你所使用的Forge版本为1711，请尝试更新的最新的Forge版本。有可能新旧Forge兼容性存在问题。

**Comment by niniubiwoc** [comment]
刚刚复现了一下bug，排查后发现
[109 99 46 104 121 112 105 120 101 108 46 105 111 0 70 77 76 0]
byte数组是长这样的
但是一变成字符串的话，ascii码为0和ascii码为32都可以表示空格
这就会造成什么呢，在末尾的0字符串其实是看不出来的，但是它还是占了一个字符位，所以使用HasSuffix在字符串末尾匹配FML字符会永远返回false，造成无法自动修复FML字段缺失
这也算是个大坑吧
诡计多端的0
新版本已修复
https://github.com/layou233/ZBProxy/actions/runs/2688333400

**Comment by OOPSgary** [comment]
快乐の发包

**Comment by PumpkinXD** [comment]
> 

呃 请问一下真的修了么，想看下具体的commit

我这边forge就是2318但连接部分加速IP就会刷类似的日志，不清楚是不是因为加速IP机房那边还在用旧版

**Comment by lycorisor** [comment]
It was fixed a long time ago
https://github.com/layou233/ZBProxy/commit/5e4d83696e9094be85fbe9a4370c73dc525e6e8e

**Comment by lycorisor** [comment]
Please change the value of "IgnoreFMLSuffix" field in the config file to false to achieve automatic correction
我也不知道**蜡油为什么要写这么反人类直觉的字段，因为您翻译一下这个字段的意思就是忽略FML后缀，所以你true就会忽略，false就不忽略

**Comment by OOPSgary** [comment]
@lycorisor 所以说为什么要用Ignore而不是其他的😭

**Comment by layou233** [comment]
> Please change the value of "IgnoreFMLSuffix" field in the config file to false to achieve automatic correction 我也不知道**蜡油为什么要写这么反人类直觉的字段，因为您翻译一下这个字段的意思就是忽略FML后缀，所以你true就会忽略，false就不忽略

因为对 FML 标识符的处理应该默认启用，所以他的缺省值 false 在逻辑上应该对应 启用 FML 标识符处理。
