### ISSUE TITLE
关于添加BAC_HWID封禁功能

### ISSUE THREAD

**Issue by aesxu2345** [layou233/ZBProxy#42]
考虑到一旦有人作弊将会导致损失一个IP并使使用同一个线路的人账户被封，所以建议兼容BAC(Badlion Anti Cheat)，这样ZBProxy一旦有玩家被目标服务器如Hypixel封禁就可以封锁作弊者HWID！

**Comment by niniubiwoc** [comment]
您好，不知道您说的是什么，但是在正常的传输过程中不会出现玩家的设备特征信息，请提交更多的文档以便我们思考

**Comment by layou233** [comment]
我没有了解过这个，请问有相关接入文档吗？  
另外，我记得即使IP被安全警报，其它用户Hypixel等级达到21+即可避免封禁，这一直是加速线路行业难以避免的问题。🤔

**Comment by OOPSgary** [comment]
@layou233 ……

**Comment by aesxu2345** [comment]
https://github.com/BadlionClient/BACPluginAPI
BAC是client-side anticheat，它是运行在玩家端的，所以不用考虑数据流的问题。如果ZBProxy接入BAC默认情况下玩家只能使用狮子端进游戏，此时一旦作弊被发现就会被狮子端ban机器！这样作弊玩家将会无法访问ZBProxy六个月。

**Comment by niniubiwoc** [comment]
问个问题，你既然限制了客户端，那怎么开挂，像vape这种热注入的没有几个支持吧
而且为了支持这个鸡肋东西我们要丢掉对于大部分客户端的支持，您觉得会有人用吗

**Comment by niniubiwoc** [comment]
而且您从Badlion的角度想想，他做这个真的是为了帮助防止作弊吗，还是为了增加自己客户端的用户数呢

**Comment by niniubiwoc** [comment]
而且不是像您所说的不要考虑数据流问题，您不考虑数据流怎么知道客户端用了BAC，这样的话您还得知道玩家的access_token(相当于就告诉你我玩家的账号密码了)才能伪造解出中间的明文数据

**Comment by OOPSgary** [comment]
@aesxu2345 我认为ZBP为的就是轻便 跑一个反作弊支持属实是不智齿

**Comment by niniubiwoc** [comment]
而且您这个BAC绕过是真的好绕过，我客户端只要注入一个BAC特有的心跳包检测就能绕过了

**Comment by layou233** [comment]
@aesxu2345 手机上看了一下，BACPluginAPI仓库里似乎不包含具体实现

**Comment by OOPSgary** [comment]
@layou233 怎么办

**Comment by layou233** [comment]
@aesxu2345 应该只是一些接口类，具体实现可能在Badlion的商业插件中。

**Comment by OOPSgary** [comment]
如果只能可以用BLC进入游戏 那么限制就会增加很多
个人不推荐加入BAC反作弊支持
Lunar已经其他客户端的用户也很多
不能忽视
