### ISSUE TITLE
如何修改hosts文件以绕过Hypixel非官方地址检测？

### ISSUE THREAD

**Issue by Hislad** [layou233/ZBProxy#43]
首先，我使用的是翻译器，所以中文可能不是最好的。
我想在ZBProxy旁边使用TCP-Proxy（https://github.com/VIPWYH2004/TCP-Proxy）。但是，如果运行TCP-Proxy，然后运行ZBProxy，ZBProxy会立即崩溃，没有任何消息。你能帮助我使ZBProxy与TCP-Proxy一起工作，或者告诉我在hosts文件中加入什么来绕过Hypixel的地址检测？你的文档中提到，编辑hosts文件可以绕过Hypixel的非官方地址检测，所以我想知道如何做到这一点。

**Comment by lycorisor** [comment]
您好，编辑hosts的原理是minecraft客户端会将这个域名放入握手包，然后传输给服务端，服务端可以检测
但是在转发程序中，我们没必要这么干，我们直接修改握手包的数据就可以了
在ZBProxy默认配置中是可以直接绕过Hypixel的非官方地址检测，不懂您为什么需要hosts，hosts是最低级的一种手段

**Comment by layou233** [comment]
> 首先，我使用的是翻译器，所以中文可能不是最好的。
> 我想在ZBProxy旁边使用TCP-Proxy（https://github.com/VIPWYH2004/TCP-Proxy）。但是，如果运行TCP-Proxy，然后运行ZBProxy，ZBProxy会立即崩溃，没有任何消息。你能帮助我使ZBProxy与TCP-Proxy一起工作，或者告诉我在hosts文件中加入什么来绕过Hypixel的地址检测？你的文档中提到，编辑hosts文件可以绕过Hypixel的非官方地址检测，所以我想知道如何做到这一点。

You have mentioned that ZBProxy crashes silently. Could I ask if you are using Windows as operating system and run it through a simple double click from explorer?  
If yes, try to run it through a console (like cmd or powershell) and it should crash with reason and you can see it. Then contact us here if you still have something confused. 😋

**Comment by layou233** [comment]
我看了一下 https://github.com/VIPWYH2004/TCP-Proxy 这个项目，感觉里面的功能和 ZBProxy 相似，并且 ZBProxy 也实现了 IP Whitelist/Blacklist 的功能。你也可以考虑全部迁移到 ZBProxy 。

**Comment by OOPSgary** [comment]
@Hislad Minecraft中的域名检测绕过属于在第一个handshake包中的目标IP 
Minecraft客户端登陆一个IP他握手包里面就是这个IP
绕过的方法就是拦下这个包 伪造一个正常链接的数据包进行发送

**Comment by OOPSgary** [comment]
> 首先，我使用的是翻译器，所以中文可能不是最好的。 我想在ZBProxy旁边使用TCP-Proxy（[https://github.com/VIPWYH2004/TCP-Proxy）。但是，如果运行TCP-Proxy，然后运行ZBProxy，ZBProxy会立即崩溃，没有任何消息。你能帮助我使ZBProxy与TCP-Proxy一起工作，或者告诉我在hosts文件中加入什么来绕过Hypixel的地址检测？你的文档中提到，编辑hosts文件可以绕过Hypixel的非官方地址检测，所以我想知道如何做到这一点。](https://github.com/VIPWYH2004/TCP-Proxy%EF%BC%89%E3%80%82%E4%BD%86%E6%98%AF%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%BF%90%E8%A1%8CTCP-Proxy%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%90%E8%A1%8CZBProxy%EF%BC%8CZBProxy%E4%BC%9A%E7%AB%8B%E5%8D%B3%E5%B4%A9%E6%BA%83%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%B6%88%E6%81%AF%E3%80%82%E4%BD%A0%E8%83%BD%E5%B8%AE%E5%8A%A9%E6%88%91%E4%BD%BFZBProxy%E4%B8%8ETCP-Proxy%E4%B8%80%E8%B5%B7%E5%B7%A5%E4%BD%9C%EF%BC%8C%E6%88%96%E8%80%85%E5%91%8A%E8%AF%89%E6%88%91%E5%9C%A8hosts%E6%96%87%E4%BB%B6%E4%B8%AD%E5%8A%A0%E5%85%A5%E4%BB%80%E4%B9%88%E6%9D%A5%E7%BB%95%E8%BF%87Hypixel%E7%9A%84%E5%9C%B0%E5%9D%80%E6%A3%80%E6%B5%8B%EF%BC%9F%E4%BD%A0%E7%9A%84%E6%96%87%E6%A1%A3%E4%B8%AD%E6%8F%90%E5%88%B0%EF%BC%8C%E7%BC%96%E8%BE%91hosts%E6%96%87%E4%BB%B6%E5%8F%AF%E4%BB%A5%E7%BB%95%E8%BF%87Hypixel%E7%9A%84%E9%9D%9E%E5%AE%98%E6%96%B9%E5%9C%B0%E5%9D%80%E6%A3%80%E6%B5%8B%EF%BC%8C%E6%89%80%E4%BB%A5%E6%88%91%E6%83%B3%E7%9F%A5%E9%81%93%E5%A6%82%E4%BD%95%E5%81%9A%E5%88%B0%E8%BF%99%E4%B8%80%E7%82%B9%E3%80%82)

Eh. Minecraft will send the handshake packet in the first time.
It contains:
Protocol Version
Server Address
Server Port
And NextState code
The servers (like hypixel) will check the Server Address and if it isnt "*.hypixel.net" or "*.hypixel.io", it will block your connection(when the client pull a status request).
When a client login to ZBProxy(EnableHostnameRewritten)  , ZBProxy will make a new Packet instead of client's packet,so the servers will think it's a normal connection.

**Comment by Hislad** [comment]
谢谢大家的帮助，我找到了我要找的东西。
