### ISSUE TITLE
能否添加实时在线玩家支持？

### ISSUE THREAD

**Issue by SkyLakeEngine** [layou233/ZBProxy#44]
在motd中，在线玩家是假的数字，它永远都是0
能否添加实时在线玩家支持？

**Comment by layou233** [comment]
好主意，在做MOTD的时候我也想过这一点，但是后面忘记了（  
计划添加，但是让我先研究一下怎么实现比较好。

**Comment by OOPSgary** [comment]
@SkyLakeEngine ncp先生你好

**Comment by layou233** [comment]
@SkyLakeEngine 可以加tg群，在主页README
