### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by LittleGriseo** [layou233/ZBProxy#48]
ZBProxy 3.0-rc.2 | Running... ______ _____ _____ _____ _____ __ __ __ __ |___ / | _ \ | _ \ | _ \ / _ \ \ \ / / \ \ / / / / | |_| | | |_| | | |_| | | | | | \ \/ / \ \/ / / / | _ { | ___/ | _ / | | | | } { \ / / /__ | |_| | | | | | \ \ | |_| | / /\ \ / / /_____| |_____/ |_| |_| \_\ \_____/ /_/ \_\ /_/ Welcome to ZBProxy 3.0-rc.2! Build Information: go1.19, linux/amd64 2022/08/31 19:12:07 Successfully loaded config from file. 2022/08/31 19:12:07 Config Reload Error : no such file or directory

**Comment by layou233** [comment]
Fixed in f7cea5a.  
btw, 这不是我本人提交的，应该是某个小鬼盗用我名字提交的 @lycorisor  
会很快进行新的Build。

**Comment by LittleGriseo** [comment]
草，我一小时前刚Fork你代码自己构建才看出来

**Comment by layou233** [comment]
新的热重载 #45 由 @lycorisor 撰写，可能存在部分离奇小问题，由他自己来解决（
