### ISSUE TITLE
我想更改我所要加速的游戏

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#5]
我想加速cubecraft的服务器，但我不会编译

**Comment by layou233** [comment]
本项目已包含了一个Workflow自动构建的脚本  
fork项目，然后更改代码，最后前往Action手动触发一个任务，Workflow会自动帮你云编译全平台的可执行程序。在编译全部结束后就可以下载。  
windows构件需要自己加上.exe后缀

**Comment by return60** [comment]
![QQ截图20210807091712](https://user-images.githubusercontent.com/68880298/128583472-504df4c7-6659-4e54-a5dd-afbe1bd9ceee.png)
有问题

**Comment by layou233** [comment]
兄弟开错workflow了，应该使用build.yml那个，那个是我已经预设好的，不会出现问题

**Comment by layou233** [comment]
No follow-up questions, unable to continue tracking the issue, temporarily closed

**Comment by layou233** [comment]
This method is deprecated due to 3.0 configuration update.  
No longer pin this issue.
