### ISSUE TITLE
Minecraft分流功能

### ISSUE THREAD

**Issue by OPNetworkLOL** [layou233/ZBProxy#50]
建议添加Minecraft分流功能

**Comment by OOPSgary** [comment]
大约是什么意思的

**Comment by OOPSgary** [comment]
你可以自己想想之前已经closed的issue

**Comment by OOPSgary** [comment]
这个只能说基本不可能实现 如果需要实现的话 ZBProxy在处理完登录包以后依旧要接管这个连接(而不是转发)

**Comment by OOPSgary** [comment]
https://t.me/Launium/10046

**Comment by layou233** [comment]
> 这个只能说基本不可能实现 如果需要实现的话 ZBProxy在处理完登录包以后依旧要接管这个连接(而不是转发)
> 不可行原因：

He is just joking.  
  
He has talked to me for this feature. Limited to the code structure, it may be hard to implement.  
I'm considering this and try to implement it in the next sub-version, like 3.1?
