### ISSUE TITLE
有虫

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#6]
在使用1.17.1进行连接时，会导致zbproxy直接崩溃，这是一个很奇怪的bug

**Comment by layou233** [comment]
刚放学，看到一个fork已经帮助我解决了protocol  number 的问题  
[https://github.com/9ikj/ZBProxy](https://github.com/9ikj/ZBProxy)  
在这里感谢一下 @9ikj ，应该也是一位中国人，不错的补丁程序  
但是鉴于我本人事实上已经有对于当前主分支的代码进行了部分修改，等待发布2.0版本，所以请见谅，目前无合并分支的打算，并非出于其它原因。  
如果有需要使用高版本代理的可以使用这位仁兄的版本  
（呃不过我可能会咕咕比较长的一段时间，刚进入高中不太适应住宿生活和学习节奏，虚的很，时间也比较少）

**Comment by layou233** [comment]
另外，对于你所说的1.17.1连接时主程序崩溃，请麻烦发送一下崩溃时的错误信息，方便我进行跟进

**Comment by return60** [comment]
但似乎这是概率问题了

**Comment by return60** [comment]
但似乎崩溃是一个概率问题，

**Comment by layou233** [comment]
问题描述为连接创建时有几率导致崩溃，在最新版ZBProxy实测不存在该问题，故暂时关闭issue，等待更多信息。
