### ISSUE TITLE
增加配置文件热重载

### ISSUE THREAD

**Issue by Xiaomckedou233** [layou233/ZBProxy#64]
每一次添加新的Lists Object都需要重新启动ZBProxy,是否可以提供一种手段或者定时热重载配置文件?

**Comment by lycorisor** [comment]
？？？？有自动热重载啊，你改了文件他会自动检测到，请下载最新版本
[](https://github.com/layou233/ZBProxy/actions/runs/3399848890)

**Comment by lycorisor** [comment]
[Click There](https://github.com/layou233/ZBProxy/actions/runs/3399848890)

**Comment by Xiaomckedou233** [comment]
啊这,但是我改了之后他并没有刷(
也是最新的3.0-rc3
