### ISSUE TITLE
关于socks

### ISSUE THREAD

**Issue by Annanoy** [layou233/ZBProxy#68]
我看这里面好像还写了通过socks代理，请问目前是否可用。

**Comment by layou233** [comment]
@Annanoy 应该是可用的

**Comment by OOPSgary** [comment]
@layou233 应该 × 只要没问题就可以 √

**Comment by Annanoy** [comment]
请问如何使用，在自动生成的ZBProxy.json中无对应选项

**Comment by layou233** [comment]
@Annanoy Type 为 socks(5) socks4 socks4a 中的一个

Network 为 tcp tcp4 tcp6 unix 中的一个

Address 是地址，例如 127.0.0.1:1080 和 [::1]:1080

**Comment by Annanoy** [comment]
{
    "Services": [
        {
            "Name": "HypixelDefault",
            "TargetAddress": "mc.hypixel.net",
            "TargetPort": 25565,
            "Listen": 25565,
            "Flow": "auto",
            "IPAccess": {
                "Mode": ""
            },
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "OnlineCount": {
                    "Max": 114514,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "IgnoreFMLSuffix": true,
                "NameAccess": {
                    "Mode": ""
                },
                "AnyDestSettings": {},
                "MotdFavicon": "{DEFAULT_MOTD}",
                "MotdDescription": "§d{NAME}§e service is working on §a§o{INFO}§r\n§c§lProxy for §6§n{HOST}:{PORT}§r"
            },
            "TLSSniffing": {
                "RejectNonTLS": false
            },
            "Outbound": {
				"Type": "socks(5)",
				"Network": "tcp",
				"Address": "username:password@127.0.0.1:1080"
            }
        }
    ],
    "Lists": {}
}

**Comment by Annanoy** [comment]
请问大概是这个样子吗

**Comment by layou233** [comment]
@Annanoy 当前版本暂不支持用户密码验证

**Comment by Annanoy** [comment]
好，谢谢

**Comment by layou233** [comment]
@Annanoy socks(5) 的意思是填写 socks 和 socks5 等效
