### ISSUE TITLE
可以将单独做一个配置文件吗

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#8]
这样方便配置

**Comment by layou233** [comment]
我当初也是这么想的，所以现在这个计划还在TODO~~咕咕~~里。  
最近在忙ZBProject多维的开发，可以看到我现在还做了个文档中心，忙完这些（大概两个月内，寒假估计能行）就必回来更新ZBProxy（立flag XD

**Comment by return60** [comment]
如果可以的话，建议配置文件中可以转发多个ip的功能。

**Comment by layou233** [comment]
新的版本已经开始编写，整个项目结构已被重构，所有的提交暂时在dev分支里，待可测试时合并到主分支

**Comment by return60** [comment]
好耶

**Comment by layou233** [comment]
已编译第一版尝鲜  
https://github.com/layou233/ZBProxy/actions/runs/1622411542  
目前配置里很多东西写了还没有实现，但是对于ZBProxy 2.0的功能都已经实现，并拥有了MOTD功能。  
增加了Linux环境的零拷贝技术支持，使用Linux Kernel提供的splice函数大幅减少缓冲区复制损耗。  
这个配置比较细，可以高度自定义，适应各种生产环境。  
剩下的东西几周内完成。（这一版我拿手机写的，全程没上过电脑，可不可用我也不知道XD）

**Comment by layou233** [comment]
在配置json里可以看到`Services`其实是个列表，我在这一版添加了同时运行多个服务的功能，可以在列表里放多个`Service`对象，程序运行时都会启动。
