### ISSUE TITLE
请问此处对err做判断的作用？

### ISSUE THREAD

**Issue by DreamwareN** [layou233/ZBProxy#81]
https://github.com/layou233/ZBProxy/blob/301b4da5957db296321944fc2f2953b4dabda0f7/service/minecraft/handler.go#L99

**Comment by layou233** [comment]
没用，之前 generateMOTD 有返回 err ，后来改了返回值然后忘记删 err 判断了（

**Comment by OOPSgary** [comment]
@DreamwareN Dreamware你发现啦(
