### ISSUE TITLE
这里重置buf的意义是什么Galaxy Code meme

### ISSUE THREAD

**Issue by OOPSgary** [layou233/ZBProxy#82]
https://github.com/layou233/ZBProxy/blob/master/service/minecraft/handler.go#L97
这边重置buf的意义是什么

**Comment by OOPSgary** [comment]
@OOPSgary 🤪🤪

**Comment by layou233** [comment]
好

**Comment by lycorisor** [comment]
这位兄弟，我希望你不要不知好歹，明早之前hypixel工会功能不更新完毕你号没了

**Comment by OOPSgary** [comment]
@lycorisor
