### ISSUE TITLE
3.0rc无法读取、创建配置文件

### ISSUE THREAD

**Issue by zevlaoxie2010** [layou233/ZBProxy#83]
3.0rc无法读取、创建配置文件
一直卡在那一行
影响最新构建

**Comment by zevlaoxie2010** [comment]
3.0rc5

**Comment by lycorisor** [comment]
您好，请提供完整的启动log，我这边测试的没问题呢
另外，请检查文件权限
`chmod 777 ZBProxy`
提升文件权限

**Comment by zevlaoxie2010** [comment]
______  _____   _____   _____    _____  __    __ __    __
|___  / |  _  \ |  _  \ |  _  \  /  _  \ \ \  / / \ \  / /
   / /  | |_| | | |_| | | |_| |  | | | |  \ \/ /   \ \/ /
  / /   |  _  { |  ___/ |  _  /  | | | |   }  {     \  /
 / /__  | |_| | | |     | | \ \  | |_| |  / /\ \    / /
/_____| |_____/ |_|     |_|  \_\ \_____/ /_/  \_\  /_/
Welcome to ZBProxy 3.0-rc.5 (301b4da)!
Build Information: go1.19.5, windows/386, CGO disabled
2023/01/26 17:59:43 Configuration file is not exists. Generating a new one...
2023/01/26 17:59:43 Successfully loaded config from file.
就卡在最后
amd64同

**Comment by zevlaoxie2010** [comment]
加载后应该会输出”Your ZBProxy is out of date! Check for the latest version at https://github.com/layou233/ZBProxy/releases“

**Comment by lycorisor** [comment]
您好，在最近的一次更新中，我们觉得检查更新没有什么意义，所以去掉了这个功能呢
https://github.com/layou233/ZBProxy/commit/8ec6b713a9ee47cf0e9ae03c5c29a6856f74382e

**Comment by zevlaoxie2010** [comment]
好的我再测一下
