### ISSUE TITLE
增加限速功能

### ISSUE THREAD

**Issue by Annanoy** [layou233/ZBProxy#84]
建议增加限制每个玩家可使用的最大宽带的功能
![397EAE85DB7AF094777BC29FFB57AAF4](https://user-images.githubusercontent.com/120258670/214854273-0317b431-ca61-4114-b739-676ccc6ba843.png)

**Comment by lycorisor** [comment]
您可以通过iptables搭配hashlimit实现呢
[hashlimit详解](https://chengqian90.com/Linux%E5%B7%A5%E5%85%B7/Iptables%E7%9A%84%E9%99%90%E9%80%9F%E6%A8%A1%E5%9D%97.html)
对于这种接近于底层的功能，我们ZBProxy暂时不会考虑在程序中加，一方面是我们所能用到的接口实现起来都不是很优雅，另一方面效率也不是很高

**Comment by OOPSgary** [comment]
@Annanoy 限速公你可以通过iptables实现 谢谢
