### ISSUE TITLE
无法启用访问控制功能

### ISSUE THREAD

**Issue by ClayPlayer233** [layou233/ZBProxy#85]
配置文件如下
```json
{
    "Services": [
        {
            "Name": "PorxyTest",
            "TargetAddress": "mc.hypixel.net",
            "TargetPort": 25565,
            "Listen": 25565,
            "Flow": "linux-zerocopy",
            "IPAccess": {
                "Mode": ""
            },
            "Minecraft": {
                "EnableHostnameRewrite": true,
                "OnlineCount": {
                    "Max": 2023,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "NameAccess": {
                    "Mode": "block",
                    "ListTags": ["names"]
                },
                "AnyDestSettings": {},
                "PingMode": "",
                "MotdFavicon": "icon.png",
                "MotdDescription": "Proxy"
            },
            "TLSSniffing": {
                "RejectNonTLS": false
            },
            "Outbound": {
                "Type": ""
            }
        }
    ],
    "Lists": {
        "names": ["123", "BotAli"],
        "iPs": ["1.1.1.1", "2.2.2.2"]
    }
}
```

**Comment by ClayPlayer233** [comment]
名字为BotAli的玩家可以进入服务器

**Comment by ClayPlayer233** [comment]
顺便问一下MotdFavicon中的String填写图片的名字还是填写URL 还是说填写路径

**Comment by BiliZheXue** [comment]
@ClayPlayer233 base64编码的64x64像素png格式图片
例:data:image/png;base64,xxxxxx

**Comment by ClayPlayer233** [comment]
谢谢！ 顺便问一下上面的问题

**Comment by lycorisor** [comment]
您好，Mode的值为block/blacklist是黑名单模式，值为allow/whitelist是白名单模式

**Comment by ClayPlayer233** [comment]
我的mode值写block BotAli依然可以进入服务器

**Comment by BiliZheXue** [comment]
@ClayPlayer233 请尝试names列表中仅含有botali

**Comment by ClayPlayer233** [comment]
无效

**Comment by layou233** [comment]
可能是最近的几次更改出了问题，我会在明天中午之前查看这个问题。

**Comment by layou233** [comment]
可能是最近的几次更改出了问题，我会在明天中午之前查看这个问题。

**Comment by BiliZheXue** [comment]
@ClayPlayer233 请尝试回退到您现在所使用版本的上个build
最新版本的AccessControl未经过测试

**Comment by lycorisor** [comment]
您好，请提交ZBProxy运行log以便我们查看问题

**Comment by ClayPlayer233** [comment]
好的 我尝试一下

**Comment by ClayPlayer233** [comment]
2023/01/29 19:51:17 Config Reload : File change detected. Reloading...
2023/01/29 19:51:17 Config Reload : Successfully reloaded Lists.
2023/01/29 19:51:27 Service LongMaoJSIP : [1131116106] [+] 113.68.88.84:5068
2023/01/29 19:51:28 Service LongMaoJSIP : [1131116106] [-] 113.68.88.84:5068 
2023/01/29 19:51:57 Service LongMaoJSIP : [1868118789] [+] 113.68.88.84:5110
2023/01/29 19:51:57 Service LongMaoJSIP : [1868118789] [-] 113.68.88.84:5110 
2023/01/29 19:52:15 Config Reload : File change detected. Reloading...
2023/01/29 19:52:15 Config Reload : Successfully reloaded Lists.
2023/01/29 19:52:47 Service LongMaoJSIP : [152016328] [+] 113.68.88.84:5154
2023/01/29 19:52:47 Service LongMaoJSIP : [152016328] [-] 113.68.88.84:5154 
2023/01/29 19:57:52 Config Reload : File change detected. Reloading...
2023/01/29 19:57:52 Config Reload : Successfully reloaded Lists.
2023/01/29 19:57:55 Config Reload : File change detected. Reloading...
2023/01/29 19:57:55 Config Reload : Successfully reloaded Lists.
2023/01/29 19:58:08 Service LongMaoJSIP : [663900515] [+] 113.68.88.84:5328
2023/01/29 19:58:08 Service LongMaoJSIP : [663900515] [-] 113.68.88.84:5328 
2023/01/29 19:58:31 Config Reload : File change detected. Reloading...
2023/01/29 19:58:31 Config Reload : Successfully reloaded Lists.
2023/01/29 19:58:39 Service LongMaoJSIP : [101465592] [+] 113.68.88.84:5366
2023/01/29 19:58:39 Service LongMaoJSIP : [101465592] [-] 113.68.88.84:5366 
2023/01/29 19:58:53 Config Reload : File change detected. Reloading...
2023/01/29 19:58:53 Config Reload : Successfully reloaded Lists.

**Comment by layou233** [comment]
@ClayPlayer233 正常配置的情况下，日志会输出加入游戏的玩家名，很奇怪这里面为什么没有……

**Comment by ClayPlayer233** [comment]
是的

**Comment by ClayPlayer233** [comment]
我尝试过了 如果我把黑名单中我的Minecraft名字移除 他就会显示 如果添加到names中 他就会不显示

**Comment by layou233** [comment]
了解到切换到同一版本的不同构建就能正常……离谱事件……
