### ISSUE TITLE
能不能添加控制台命令支持？

### ISSUE THREAD

**Issue by VIPWYH2004** [layou233/ZBProxy#86]
能否在控制台中实现通过指令修改部分配置文件内容
如:
`whitelist add <Player>` 添加玩家白名单
`whitelist del <Player>` 删除玩家白名单
`list` 输出当前使用该节点的玩家消息和IP

**Comment by lycorisor** [comment]
您好，ZBProxy支持热重载功能，所以您可以自己在运行的情况下直接修改配置文件，或者写一个脚本实现，ZBProxy目前并不打算实现命令行功能，因为容易和配置文件混淆
