### ISSUE TITLE
求助：获取不到在线玩家数

### ISSUE THREAD

**Issue by ky678** [layou233/ZBProxy#88]
服务器上有一个玩家但是游戏界面显示 0/2023
{
    "Services": [
        {
            "Name": "*******",
            "TargetAddress": "**********",
            "TargetPort": *****,
            "Listen": *****,
            "Flow": "linux-zerocopy",
            "IPAccess": {
                "Mode": "",
                "ListTags": []
            },
            "Minecraft": {
                "EnableHostnameRewrite": false,
                "RewrittenHostname": "",
                "OnlineCount": {
                    "Max": 2023,
                    "Online": -1,
                    "EnableMaxLimit": false
                },
                "IgnoreFMLSuffix": false,
                "NameAccess": {
                    "Mode": "",
                    "ListTags": []
                },
                "EnableAnyDest": false,
                "AnyDestSettings": {},
                "PingMode": "",
                "MotdFavicon": "",
                "MotdDescription": "*****"
            },
            "TLSSniffing": {
                "RejectNonTLS": false,
                "RejectIfNonMatch": false,
                "SNIAllowListTags": []
            },
            "Outbound": {
                "Type": "",
                "Network": "tcp",
                "Address": ""
            }
        }
    ],
    "Lists": {}
}

**Comment by lycorisor** [comment]
您好，请提交运行log

**Comment by ky678** [comment]
抱歉，我指的是无法显示服务器的实时在线人数而不是使用代理服务器的人数，希望能添加显示服务器人数而非代理人数的选项

**Comment by BiliZheXue** [comment]
@ky678 这个功能感觉无关紧要
可以选择在多人游戏列表中添加一个mc.hypixel.net解决
😘
