### ISSUE TITLE
请求增加ss代理支持和链式代理功能

### ISSUE THREAD

**Issue by XiChenBaBa** [layou233/ZBProxy#92]
想直接用机场的

**Comment by layou233** [comment]
目前已经支持 SOCKS 4/4A/5 出站，可以配合 ss-rust、*ray、sing-box 使用。

**Comment by OOPSgary** [comment]
@XiChenBaBa 机场的不是很现实 延迟不高吗

**Comment by XiChenBaBa** [comment]
> 目前已经支持 SOCKS 4/4A/5 出站，可以配合 ss-rust、*ray、sing-box 使用。

性能不够，便宜国内机器在win下这样实现CPU会直接跑满

**Comment by layou233** [comment]
走代理功能在 3.0-rc.3 release 里就正式发布了，当时写的 release note 是：

> 同时，SOCKS 系出站协议同样支持 Flow 功能，在 Linux 上可以做到零拷贝。
这类似于“前置代理”，方便通过一些隧道程序传输数据。
未来有计划继续支持 HTTP 代理协议，Shadowsocks 等协议暂时不在计划之列。

不支持 Shadowsocks 的原因是，我认为在 ZBProxy 里再实现一套加密代理协议会使代码变得更冗余，完全可以复用现有的代理工具集。

性能方面，试试 sing-box ，应该不至于性能不足。

**Comment by XiChenBaBa** [comment]
> 

OK感谢，我去试试sing-box，之前用的xray，非常占用性能
