### ISSUE TITLE
MOTD图片怎么改

### ISSUE THREAD

**Issue by kxkl2077** [layou233/ZBProxy#95]
"MotdFavicon": "{DEFAULT_MOTD}"
这是默认MOTD，我不明白这里面应该填什么？填写图片路径？还是图片名称？
MotdFavicon : ""

**Comment by layou233** [comment]
@kxkl2077 见文档

**Comment by kxkl2077** [comment]
我是个小白，就是string (base64 png, 64*64) 没搞懂...

**Comment by layou233** [comment]
@kxkl2077 需要一个 64*64 尺寸的 png 图片，网上找一个 png 转 base64 格式的工具进行转换，然后把转换出来的字符串填进去。

**Comment by kxkl2077** [comment]
哦，明白了

**Comment by layou233** [comment]
@kxkl2077 如果使用没有问题，请关闭 issue

**Comment by layou233** [comment]
我们更新了文档并且写了一个我们官方的图片转 base64 转换器。简单但够用。

https://launium.com/app/file-base64
