### ISSUE TITLE
一直登入中，终端刷屏玩家重复进入

### ISSUE THREAD

**Issue by lxyddice** [layou233/ZBProxy#98]
![uTools_1684461308797](https://github.com/layou233/ZBProxy/assets/95132858/e39b59bd-dced-4d92-8813-22968511552d)
![uTools_1684461308797](https://github.com/layou233/ZBProxy/assets/95132858/5717cffc-9c0c-4798-adc6-7ba70e5b1a7e)

**Comment by lxyddice** [comment]
![uTools_1684461365256](https://github.com/layou233/ZBProxy/assets/95132858/a1910835-28b9-4726-bf8a-54832aebfbcd)

**Comment by BiliZheXue** [comment]
@lxyddice 日志中打印出来了一个failed to dial server
请检查转发的服务器地址是否配置正确及服务器是否在线

**Comment by layou233** [comment]
我猜测是把目标IP设为 127.0.0.1 然后回环自己了。。

RemoteAddr 用于设定转发的目标服务器，而不是本地监听地址。

**Comment by lycorisor** [comment]
大胆一点，他是之前做了hosts伪造没有改过来

**Comment by lxyddice** [comment]
感谢，因为看到网上教程说改hosts文件

**Comment by lxyddice** [comment]
感谢！因为网上教程说是改hosts文件，后来才知道是过时教程
